name: 🐧 Build and Test

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake build-essential \
          liblua5.3-0 liblua5.3-dev libglm-dev libglfw3-dev \
          libassimp-dev libfreeimage-dev rapidjson-dev \
          libbullet-dev libfreetype6-dev
    - name: Build All Projects ( Linux )
      run: cmake -S . -B out -DBUILD_RUNTIME=ON -DBUILD_TESTING=ON && cmake --build out

    - name: Run Tests
      run: ctest --test-dir out --output-on-failure
